- name: ACI Setup
  hosts: apic
  connection: local
  gather_facts: false
  vars: 
      ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - variable_file.yaml

  tasks:

  - name: CREATE XML POSTS FROM TEMPLATES
    template: src={{ item.src }} dest={{ item.dest }}
    with_items:
      - { src: 'unManagedMode_posts/create_unmanged_ldev.j2',      dest: 'unManagedMode_posts/create_unmanged_ldev.xml' }

  - name: CREATE UNMANAGED LOGICAL DEVICE
    aci_rest:
      action: "post"
      uri: "/api/node/mo/uni/tn-{{tenant_name}}.xml"
      config_file: "{{ item }}"
      host: "{{inventory_hostname}}"
      validate_certs: false 
      username: "{{ username }}"
      password: "{{ password }}"
    with_items:
     - "unManagedMode_posts/create_unmanged_ldev.xml"
