- name: CONFIGURING VLAN AND SELF-IP
  hosts: bigips
  connection: local
  gather_facts: false

  vars_files:
    - variable_file.yaml
# este se tiene que revisar porque al pareecr los valores de las VALN estan al reves
#+ pero asi funcion :/

  tasks:

  - name: ADDING PROVIDER VLAN
    bigip_vlan:
      server: "{{inventory_hostname}}"
      user: "{{ user }}"
      password: "{{ pass }}"
      name: "{{tenant_name}}_{{consumer_vlan_name}}"
      tag: "{{consumer_vlan}}"
      tagged_interfaces:
      - "1.1"
      validate_certs: False
    delegate_to: localhost

  - name: ADDING CONSUMER VLAN
    bigip_vlan:
      server: "{{inventory_hostname}}"
      user: "{{ user }}"
      password: "{{ pass }}"
      name: "{{tenant_name}}_{{provider_vlan_name}}"
      tag: "{{provider_vlan}}"
      tagged_interfaces:
      - "1.2"
      validate_certs: False
    delegate_to: localhost

  - name: CONFIGURING PROVIDER SELF-IP
    bigip_selfip:
      server: "{{inventory_hostname}}"
      user: "{{ user }}"
      password: "{{ pass }}"
      validate_certs: False
      name: "{{sipExname}}"
      address: "{{sipExaddr}}"
      netmask: "{{sipExnmask}}"
      vlan: "{{tenant_name}}_{{consumer_vlan_name}}"
    delegate_to: localhost

  - name: CONFIGURING CONSUMER SELF-IP
    bigip_selfip:
      server: "{{inventory_hostname}}"
      user: '{{user}}'
      password: "{{pass}}"
      validate_certs: "false"
      name: "{{sipINTname}}"     
      address: "{{sipINTaddr}}"
      netmask: "{{sipINTnmask}}"
      vlan: "{{tenant_name}}_{{provider_vlan_name}}"


