- name: CREATE POOL & POOL MEMBERS 
  hosts: bigips 
  connection: local
  gather_facts: false
  vars:
   ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - variable_file.yaml

  tasks:

  - name: CREATING POOL
    bigip_pool:
        server  : "{{server}}"
        user: "{{user}}"
        pass: "{{pass}}"
        validate_certs: False
        state: "present"
        name: "{{tenant_name}}_http-pool"
        lb_method: "round-robin"
        # delegate_to: localhost

  - name: ADDING POOL MEMBERS
    bigip_pool_member:
        server  : "{{server}}"
        user: "{{user}}"
        pass: "{{pass}}"
        pool: "{{tenant_name}}_http-pool"
        host: "{{item.host}}"
        port: "{{item.port}}"
        validate_certs: False
    with_items: "{{pool_members}}"
    delegate_to: localhost 
