- name: CREATING VIP FOR WEB SERVICES
  hosts: bigips
  connection: local
  gather_facts: false
  vars:
   ansible_python_interpreter: /usr/bin/python3

  vars_files:
    - variable_file.yaml

  tasks:
  - name: ADDING VIRTUAL SERVER
    bigip_virtual_server:
         server: "{{server}}"
         user: "{{ user }}"
         password: "{{ pass }}"
         name: "{{tenant_name}}_http_vs"
         destination: "{{vip_ip}}"
         port: "{{vip_port}}"
         enabled_vlans: 
          - "{{tenant_name}}_{{consumer_vlan_name}}"
          - "{{tenant_name}}_{{provider_vlan_name}}"
         pool: "{{tenant_name}}_http-pool"
         snat: "automap"
         validate_certs: False
    delegate_to: localhost

